#version: "3.9"
#services:
#  db:
#    image: postgres:latest
#    container_name: db
#    restart: always
#    environment:
#      POSTGRES_PASSWORD: 1
#      POSTGRES_DB: study-center
#      POSTGRES_USER: postgres
#    ports:
#      - "5432:5432"
#    volumes:
#      - postgres-data:/var/lib/postgresql/data
#  app:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    container_name: springboot-crud
#    restart: always
#    environment:
#      DATABASE_HOST: 1
#      DATABASE_PORT: 5432
#      DATABASE_NAME: study-center
#      DATABASE_USER: postgres
#      DATABASE_PASSWORD: 1
#    ports:
#      - "8080:8080"
#    depends_on:
#      - db
#  jira:
#    image: atlassian/jira-software:latest
#    ports:
#      - 8888:8080
#    volumes:
#      - jira_data:/var/atlassian/application-data/jira
#    environment:
#      - JVM_MINIMUM_MEMORY=1024m
#      - JVM_MAXIMUM_MEMORY=4096m
#      - ATL_DB_TYPE=postgresql
#      - ATL_JDBC_URL=jdbc:postgresql://localhost:5432/jira
#      - ATL_JDBC_USER=postgres
#      - ATL_JDBC_PASSWORD=1
#    networks:
#      - jira_network
#volumes:
#  postgres-data: