#version: "3.9"
#services:
#  db:
#    image: postgres:latest
#    container_name: db
#    restart: always
#    environment:
#      POSTGRES_PASSWORD: 1
#      POSTGRES_DB: study-center
#      POSTGRES_USER: postgres
#        - HOSTNAME=postgres-db
#    ports:
#      - "5432:5432"
#    volumes:
#      - postgres-data:/var/lib/postgresql/data
#volumes:
#  postgres-data: