#version: "3.9"
#services:
#  db:
#    image: postgres:latest
#    container_name: db
#    restart: always
#    environment:
#      POSTGRES_PASSWORD: 1
#      POSTGRES_DB: study-center
#      POSTGRES_USER: postgres
#    ports:
#      - "5432:5432"
#    volumes:
#      - postgres-data:/var/lib/postgresql/data
#  app:
#    image: leaderunlimit/study-center
#    container_name: hub-study-center
#    restart: always
#    environment:
#      DATABASE_HOST: 1
#      DATABASE_PORT: 5432
#      DATABASE_NAME: study-center
#      DATABASE_USER: postgres
#      DATABASE_PASSWORD: 1
#    ports:
#      - "8080:8080"
#    depends_on:
#      - db
#volumes:
#  postgres-data: