#image: docker:20.10.16
#
#services:
#  - docker:20.10.16-dind
#
#stages:
#  - stop-service
#  - build-image
#  - deploy
#
#stop_service_job:
#  stage: stop-service
#  script:
#    - echo starting undeploy job...
#    - docker compose -f study-center-compose.yml down
#    - echo top-service job finished.
#
#build_image:
#  stage: build-image
#  script:
#    - echo starting build-image job...
#    - docker build -t study-center-api:v1.0.0 .
#    #    - docker rmi $(docker images -f "dangling=true" -q)
#    - echo build-image job finished.
#
#deploy_job:
#  stage: deploy
#  script:
#    - echo starting deploy job...
#    - docker compose -f study-center-compose.yml up -d
#    - echo deploy job finished.
#  #  when: manual
#  only:
#    - main
#    - develop
#  needs: ["stop_service_job", "build_image"]
##  needs:
##    - job: build_image
##      optional: true
##    - job: undeploy_job
##      optional: true